apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: autovote
data:
  default.conf: |
    server {
        listen 80;

        # Frontend Static Files
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Health Check Route
        location /healthz {
            access_log off;
            proxy_pass http://Backend-service:3000/healthz;
            proxy_set_header Host $host;
        }

        # API Proxy
        location /api/ {
            proxy_pass http://Backend-service:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }